### ISSUE TITLE
Flash detection seems broken on OSX

### ISSUE THREAD

**Issue by eht16** [stephenmcd/filebrowser-safe#42] opened 2015-02-07 13:09 UTC
It seems like the flash detection in templates/filebrowser/upload.html is broken on recent OSX systems.

At least two customers reported that they can't upload any files because there is no upload button. Since I don't own a OSX system nor do I have access to one, I cannot debug this properly, unfortunately.

I got the following screenshot where the grey box is simply empty instead of showing a upload button as it is expected:
![filebrowser_safe_flash_upload](https://cloud.githubusercontent.com/assets/617017/6092110/02e3c1e8-aec6-11e4-92f1-d42e3416cbcc.png)

osx 10.1.1
Safari 8.0

For now, as a quick'n'dirty workaround, I have overridden the upload.html template resulting in the following diff:

```diff
--- ../venv/lib/python2.7/site-packages/filebrowser_safe/templates/filebrowser/upload.html	2015-02-07 13:21:15.417565000 +0100
+++ templates/filebrowser/upload.html	2015-02-07 13:22:12.984231662 +0100
@@ -8,7 +8,6 @@
     {{ block.super }}
     <link rel="stylesheet" type="text/css" href="{% static "grappelli/css/forms.css" %}" />
     <link rel="stylesheet" type="text/css" href="{{ settings_var.URL_FILEBROWSER_MEDIA }}css/filebrowser.css" />
-    <link rel="stylesheet" type="text/css" href="{{ settings_var.URL_FILEBROWSER_MEDIA }}uploadify/uploadify.css" />
 {% endblock %}
 
 <!-- JAVASCRIPTS -->
@@ -16,7 +15,6 @@
     {{ block.super }}
     <script type="text/javascript" src="../../jsi18n/"></script>
     <script type="text/javascript" src="{{ settings_var.URL_FILEBROWSER_MEDIA }}uploadify/jquery-1.4.2.min.js"></script>
-    <script type="text/javascript" src="{{ settings_var.URL_FILEBROWSER_MEDIA }}uploadify/jquery.uploadify.v2.1.4.min.js"></script>
     <script type="text/javascript" src="{{ settings_var.URL_FILEBROWSER_MEDIA }}uploadify/swfobject.js"></script>
     <script type="text/javascript">
     jQuery(function($) {
@@ -25,48 +23,6 @@
         if (proxy) {
             proxy += '?u=';
         }
-
-        var hasFlash = ((typeof navigator.plugins != "undefined" && typeof navigator.plugins["Shockwave Flash"] == "object") || (window.ActiveXObject && (new ActiveXObject("ShockwaveFlash.ShockwaveFlash")) != false));
-        if (hasFlash) {
-            $('#id_file').uploadify({
-                'uploader'          : proxy + '{{ settings_var.URL_FILEBROWSER_MEDIA }}uploadify/uploadify.swf',
-                'script'            : '{% url "fb_do_upload" %}',
-                'scriptData'        : {'session_key': '{{session_key}}'},
-                'checkScript'       : '{% url "fb_check" %}',
-                'cancelImg'         : '{{ settings_var.URL_FILEBROWSER_MEDIA }}uploadify/cancel.png',
-                'auto'              : false,
-                'folder'            : '{{ query.dir|escapejs }}',
-                'multi'             : true,
-                'fileDesc'          : '{% for extension in settings_var.EXTENSIONS.items %}{% ifnotequal extension.0 'Folder' %}{% for item in extension.1 %}*{{ item|safe }};{% endfor %}{% endifnotequal %}{% endfor %}',
-                'fileExt'           : '{% for extension in settings_var.EXTENSIONS.items %}{% ifnotequal extension.0 'Folder' %}{% for item in extension.1 %}*{{ item|safe }};{% endfor %}{% endifnotequal %}{% endfor %}',
-                'sizeLimit'         : {{ settings_var.MAX_UPLOAD_SIZE|unlocalize }},
-                'scriptAccess'      : 'always',
-                'queueSizeLimit'    : 50,
-                'simUploadLimit'    : 1,
-                'width'             : 300,
-                'height'            : 30,
-                'hideButton'        : false,
-                'wmode'             : 'transparent',
-                'removeCompleted'   : false,
-                'onAllComplete' : function(event,data) {location = '{% url "fb_browse" %}{% query_string '' 'p' %}'},
-                translations        : {
-                                      browseButton: '{% trans "BROWSE" %}',
-                                      error: '{% trans "An Error occured" %}',
-                                      completed: '{% trans "Completed" %}',
-                                      replaceFile: '{% trans "Do you want to replace the file" %}',
-                                      unitKb: '{% trans "KB" %}',
-                                      unitMb: '{% trans "MB" %}'
-                }
-            });
-            $('input:submit').click(function(){
-                $('#id_file').uploadifyUpload();
-                return false;
-            });
-            $('a.deletelink').click(function(evt){
-                    $('#id_file').uploadifyClearQueue();
-                    return false;
-            });
-        }
     });
     </script>
 {% endblock %}
```

Removing the flash detection and uploadify code completely seems to help for now by falling back to JS upload.

I don't necessarily recommend to remove the uploadify/flash code completely, maybe it can be fixed easily instead. As said above, unfortunately, I cannot help in debugging/fixing since I don't have such a system :(.

**Comment by stephenmcd** [comment] 2015-02-08 23:40
We've an open issue for replacing the use of Flash if you're interested in resolving this properly:

https://github.com/stephenmcd/filebrowser-safe/issues/33

I can't reproduce the error you're describing either.

**Comment by jasmjasm** [comment] 2015-05-01 17:03
Hi all,
I've the same problem on production Mac pro server (10.10.3). But in my development machine Macbook pro (10.10.3) i don't have this problem.

![subir](https://cloud.githubusercontent.com/assets/12201274/7433642/1d3a7482-eff9-11e4-871c-8a9006bb44af.png)

When i try to upload a file raises the following error.

![error_upload](https://cloud.githubusercontent.com/assets/12201274/7433675/603f5590-eff9-11e4-987d-92d27cc73ceb.png)

I've compared both apache's access_log and this additional line is generated in development machine.

**"GET /asset_proxy/u=/static/filebrowser/uploadify/uploadify.swf HTTP/1.1"**

Any idea please.

Thanks!

**Comment by jasmjasm** [comment] 2015-05-02 11:47
If you're using a virtualenv, you must verify if filebrowser-safe is correctly installed.

**Comment by christianwgd** [comment] 2015-07-22 19:19
Setting SECURE_CONTENT_TYPE_NOSNIFF to False (default) in settings.py brings the upload button back...

**Comment by WarmongeR1** [comment] 2016-02-05 13:13
@christianwgd  +1, Thanks, It works!

**Comment by stephenmcd** [comment] 2016-03-12 20:29
Flash widget has now been removed.

**Closed by stephenmcd** 2016-03-12 20:29 UTC
